# -*- mode: conf; -*-

top-title: 临高启明

author:
  name: lingaoqiming
  email: lingaoqiming2104@sina.com
  github: lingaoqiming

markdown: kramdown
permalink: none
baseurl: /lingaoqiming
img_url: /lingaoqiming/images
font_url: /lingaoqiming/fonts

collections:
  characters:
    output: true
